name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'dbt_training'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  default_string: 'N/A'


seeds:
  +schema: public


models:
  dbt_training:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      warehouse:
        +schema: warehouse
      reporting:
        +schema: reporting 
