dbt_training:
  outputs:
    dev:
      account: jza01567
      database: ANALYTICS_DEV
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: DBT_TRAINING
      schema: DBT_KIRAN
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: DBT_TRAINING_WH
    prod:
      account: jza01567
      database: ANALYTICS
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: DBT_TRAINING
      schema: DBT_KIRAN
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: DBT_TRAINING_WH

  target: dev
